
package com.sk.WebServicesProject1Respose;

import jakarta.jws.WebMethod;

import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Employee", targetNamespace = "http://WebServicesProject1.sk.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Employee {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "add", targetNamespace = "http://WebServicesProject1.sk.com/", className = "com.sk.webservicesproject1.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://WebServicesProject1.sk.com/", className = "com.sk.webservicesproject1.AddResponse")
    @Action(input = "http://WebServicesProject1.sk.com/Employee/addRequest", output = "http://WebServicesProject1.sk.com/Employee/addResponse")
    public int add(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

}
