
package com.sk.WebServicesProject1Respose;

import java.net.MalformedURLException;

import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EmployeeService", targetNamespace = "http://WebServicesProject1.sk.com/", wsdlLocation = "http://localhost:9998/WebServicess/test1?wsdl")
public class EmployeeService
    extends Service
{

    private final static URL EMPLOYEESERVICE_WSDL_LOCATION;
    private final static WebServiceException EMPLOYEESERVICE_EXCEPTION;
    private final static QName EMPLOYEESERVICE_QNAME = new QName("http://WebServicesProject1.sk.com/", "EmployeeService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9998/WebServicess/test1?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EMPLOYEESERVICE_WSDL_LOCATION = url;
        EMPLOYEESERVICE_EXCEPTION = e;
    }

    public EmployeeService() {
        super(__getWsdlLocation(), EMPLOYEESERVICE_QNAME);
    }

    public EmployeeService(WebServiceFeature... features) {
        super(__getWsdlLocation(), EMPLOYEESERVICE_QNAME, features);
    }

    public EmployeeService(URL wsdlLocation) {
        super(wsdlLocation, EMPLOYEESERVICE_QNAME);
    }

    public EmployeeService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EMPLOYEESERVICE_QNAME, features);
    }

    public EmployeeService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EmployeeService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Employee
     */
    @WebEndpoint(name = "EmployeePort")
    public Employee getEmployeePort() {
        return super.getPort(new QName("http://WebServicesProject1.sk.com/", "EmployeePort"), Employee.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Employee
     */
    @WebEndpoint(name = "EmployeePort")
    public Employee getEmployeePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://WebServicesProject1.sk.com/", "EmployeePort"), Employee.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EMPLOYEESERVICE_EXCEPTION!= null) {
            throw EMPLOYEESERVICE_EXCEPTION;
        }
        return EMPLOYEESERVICE_WSDL_LOCATION;
    }

}
